[package]
name = "hyper-rustls"
version = "0.19.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
bytes = "0.5.2"
ct-logs = { version = "^0.6.0", optional = true }
futures-util = "0.3.1"
hyper = { version = "0.13.0", default-features = false, features = ["tcp"] }
rustls = "0.16"
tokio = "0.2.8"
tokio-rustls = "0.12.1"
webpki = "^0.21.0"
rustls-native-certs = { version = "^0.1.0", optional = true }

[dev-dependencies]
tokio = { version = "0.2.8", features = ["io-std", "macros", "dns", "stream"] }

[features]
default = ["tokio-runtime"]
tokio-runtime = ["hyper/runtime", "ct-logs", "rustls-native-certs"]

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["tokio-runtime"]

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["tokio-runtime"]
